Makefile: pip install without --user
Travis CI doesn't like it:

    ERROR: Can not perform a '--user' install. User site-packages are
    not visible in this virtualenv.

On the other hand, in environments that the user doesn't have permission
to the normal site-packages, pip falls back to the user install:

    Defaulting to user installation because normal site-packages is not
    writeable